# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# example.py
# Created on: 2015-06-23 21:32:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
CAD_Polygons_Gaeta_SE = "CAD_Polygons_Gaeta_SE"
NDM_302_Schema_UTM33_EGM08_GaetaSE_working_gdb = "C:\\Users\\Jeff\\Desktop\\Github\\CN_Tools\\Reference\\NDM_302_Schema_UTM33_EGM08_GaetaSE_working\\NDM_302_Schema_UTM33_EGM08_GaetaSE_working.gdb"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(CAD_Polygons_Gaeta_SE, "NEW_SELECTION", "Level = 4 AND Layer = 'VA_ROAD_EASP' AND Color = 3 AND Linetype = 'LongDashed' AND LineWt = 0")

# Process: Create Feature Class
arcpy.CreateFeatureclass_management(NDM_302_Schema_UTM33_EGM08_GaetaSE_working_gdb, "slab_area_A", "POLYGON", "CAD_Polygons_Gaeta_SE", "DISABLED", "DISABLED", "", "", "0", "0", "0")

